### ISSUE TITLE
gitinclude not recognised

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/birdhouse-docs#53]
some of the gitinclude are not showing up

https://birdhouse.readthedocs.io/en/latest/tutorial_birds.html

**Comment by nilshempelmann** [comment]
Warning message might be the key: 
```
From https://github.com/Ouranosinc/pavics-sdi
 * branch            HEAD       -> FETCH_HEAD
git: 'co' is not a git command. See 'git --help'.
The most similar commands are
	commit
	clone
	log
```
I included an `.gitconfig` with the alias ... but `co` is still not recognized. 

Any ideas?

**Comment by tlvu** [comment]
@nilshempelmann looks like you can not checkin a `.gitconfig` file since for it to be active, it's location should have been in `<checkout>/.git/` folder which you do not have access to for commit, see https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Where-system-global-and-local-Windows-Git-config-files-are-saved

**Comment by nilshempelmann** [comment]
@tlvu I see. 
So, may be including `git config --global alias.co checkout` in the Make file could solve the issue?

**Comment by nilshempelmann** [comment]
At least travis is happy: 
`https://travis-ci.org/github/bird-house/birdhouse-docs/builds/733316928#L585`
